name: CI/CD with Docker and VerceL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kevinr08
          password: Kevincraft54

      - name: Build Docker image
        run: docker build -t kevinr08/frontend .

      - name: Push Docker image to Docker Hub
        run: docker push kevinr08/frontend

      - name: Deploy to Vercel
        run: |
          npm install --global vercel
          vercel pull --yes --environment=production --token=38KtTfoizDDgXsbgKeqO44tf
          vercel build --prod --token=38KtTfoizDDgXsbgKeqO44tf --yes
          vercel deploy --prebuilt --prod --token=38KtTfoizDDgXsbgKeqO44tf --yes
        env:
          VERCEL_TOKEN: 38KtTfoizDDgXsbgKeqO44tf
          VERCEL_ORG_ID: team_H6lknTBP4ChWtZaLmCMgI0rS
          VERCEL_PROJECT_ID: prj_lX3U1bxbE7k59bcY8Tqh5Npgg2Bq
